# Generated by Django 4.2.20 on 2025-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_description',
            field=models.TextField(default='لا يوجد وصف'),
        ),
    ]
