# Generated by Django 4.2.20 on 2025-04-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_booking_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_description',
        ),
    ]
